#!/bin/bash

APP_DIR=app-root/runtime/repo

cat $APP_DIR/requirements.txt | while read line; do
    if echo $line | grep Test; then
        break
    fi
    echo $line >> $APP_DIR/requirements-runtime.txt
done
mv $APP_DIR/requirements-runtime.txt $APP_DIR/requirements.txt

